"""provenance.status: per-layer conformance dashboard.

Reports the running install's status against the eight-layer
WarrantOS architecture diagram plus the foundation row. Output
states per layer:

- **BUILT**: full SPEC SHALLs met with code + test coverage +
  runtime enforcement.
- **PARTIAL**: code present; one or more SHALLs deferred or
  discipline-only.
- **STARTER**: code present but explicitly documented as a starter
  surface that needs corpus / threat-model extension before
  production use.
- **NOT BUILT**: no code; documented as a v1.0+ deferral.

The status data is generated by inspecting the installed modules
(presence of classes, functions, entry points). It is not a test
suite; failing tests still report the module as present. The intent
is to give a fresh contributor or auditor a single-screen view of
which layers are real today.

Stdlib only. Python 3.8 compatible.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from importlib import import_module
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class LayerStatus:
    """Status of one layer / gate / foundation item."""

    layer_id: str
    name: str
    status: str  # BUILT | PARTIAL | STARTER | NOT_BUILT
    module: str
    surfaces: List[str] = field(default_factory=list)
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "layer_id": self.layer_id,
            "name": self.name,
            "status": self.status,
            "module": self.module,
            "surfaces": list(self.surfaces),
            "notes": self.notes,
        }


def _module_has(module_path: str, *names: str) -> bool:
    """Return True if every name exists on the named module.

    The canonical namespace for this package is `warrantos.provenance.*`.
    For backward compatibility the status rows are written with the bare
    `provenance.*` path, so this helper tries the `warrantos.`-prefixed
    module first and falls back to the bare path. This keeps the status
    report accurate whether the install resolves `provenance` to the
    `warrantos.provenance` namespace or to a legacy top-level alias.

    Tolerant: returns False on ImportError or AttributeError so that a
    partially-installed package still produces a useful status report.
    """
    candidates = (module_path,)
    if module_path.startswith("provenance."):
        candidates = ("warrantos." + module_path, module_path)
    elif module_path == "provenance":
        candidates = ("warrantos.provenance", module_path)

    for candidate in candidates:
        try:
            mod = import_module(candidate)
        except ImportError:
            continue
        if all(hasattr(mod, n) for n in names):
            return True
    return False


def _role_registry_complete() -> bool:
    """Return True if the role registry resolves all six SPEC-F-S002 roles.

    Tolerant: any import/attribute failure returns False so a partial
    install does not crash the status report.
    """
    try:
        mod = None
        for candidate in ("warrantos.provenance.roles", "provenance.roles"):
            try:
                mod = import_module(candidate)
                break
            except ImportError:
                continue
        if mod is None:
            return False
        required = getattr(mod, "REQUIRED_ACTOR_ROLE_IDS", None)
        actor_roles = getattr(mod, "ACTOR_ROLES", None)
        if required is None or actor_roles is None:
            return False
        # The six canonical roles SHALL be present (SPEC-F-S002).
        return len(set(required)) == 6 and len(actor_roles) == 6
    except Exception:
        return False


def _repo_file_exists(relative_path: str) -> bool:
    """Return True if `relative_path` exists under the repository root.

    The repo root is located relative to this module
    (warrantos/provenance/status.py -> two parents up is the repo root).
    Tolerant: returns False on any path error.
    """
    try:
        from pathlib import Path
        repo_root = Path(__file__).resolve().parents[2]
        return (repo_root / relative_path).is_file()
    except Exception:
        return False


def collect_status() -> List[LayerStatus]:
    """Return the full per-layer status list.

    Each layer's status is computed against the running install:
    presence of the relevant module symbols decides BUILT vs the
    documented partial / starter / not-built reading.
    """
    rows: List[LayerStatus] = []

    # ---------- Eight layers ----------
    rows.append(LayerStatus(
        layer_id="L1",
        name="Context Classification (11 classes)",
        status="BUILT" if _module_has(
            "provenance.context_admissibility", "classify_context"
        ) else "NOT_BUILT",
        module="provenance.context_admissibility",
        surfaces=["classify_context()", "ContextItem dataclass"],
        notes="11 canonical SPEC §2.2 classes via regex; SPEC-L1-S005 review-role gating via source_agent kwarg.",
    ))

    rows.append(LayerStatus(
        layer_id="L2",
        name="Provenance Ledger (5 sub-ledgers + override)",
        status="BUILT" if _module_has(
            "provenance.ledger_write", "enable_append_only_triggers"
        ) else "PARTIAL",
        module="provenance.ledger_write, provenance.overrides",
        surfaces=[
            "schema/provenance.sql",
            "enable_append_only_triggers() [INV-004 ENFORCED v0.9]",
            "human_override trigger installed via overrides.py CREATE TABLE",
        ],
        notes="INV-004 storage-level enforcement added in v0.9 via SQLite BEFORE UPDATE triggers.",
    ))

    rows.append(LayerStatus(
        layer_id="L3",
        name="Applied Insight Compiler",
        status="BUILT" if _module_has(
            "provenance.ledger_write", "persist_context_transform"
        ) else "PARTIAL",
        module="provenance.context_admissibility, provenance.ledger_write",
        surfaces=["derive_requirement()", "persist_context_transform()"],
        notes="SPEC-L3-N001 closure: persist_context_transform() writes the ledger row per derived requirement (v0.9).",
    ))

    rows.append(LayerStatus(
        layer_id="L4",
        name="Context Admissibility Engine (6 actor roles)",
        status="BUILT",
        module="provenance.context_admissibility, provenance.cbom",
        surfaces=[
            "ContextItem.can_be_seen_by / cannot_be_seen_by",
            "CBOM.actor_identity (6 roles per SPEC §5.2)",
        ],
        notes="Per-item flags + 6-role actor identity in CBOM v0.2.",
    ))

    rows.append(LayerStatus(
        layer_id="L5",
        name="Clean-Room Writer Pack (5 sections)",
        status="BUILT" if _module_has(
            "provenance.writer_pack", "compile_writer_pack"
        ) else "NOT_BUILT",
        module="provenance.writer_pack",
        surfaces=[
            "compile_writer_pack()",
            "WriterPack dataclass with 5 SPEC §6.2 sections",
        ],
        notes="Clean Brief / Approved Sources / Style Rules / Acceptance Tests / Banned Residue.",
    ))

    rows.append(LayerStatus(
        layer_id="L6",
        name="Clean-Room Generation (discipline + subprocess isolation)",
        status="BUILT" if _module_has(
            "provenance.clean_room", "run_clean_room_subprocess"
        ) else "PARTIAL",
        module="provenance.clean_room",
        surfaces=[
            "prepare_invocation() [discipline mode, SPEC-L6-S001]",
            "run_clean_room_subprocess() [Level 2, SPEC-L6-R001]",
        ],
        notes="WarrantOS does not call any LLM itself. The caller invokes their writer model through the InvocationPlan.",
    ))

    # ---------- Layer 7: five gates ----------
    rows.append(LayerStatus(
        layer_id="L7-G1",
        name="G1 Prose Boundary",
        status="BUILT",
        module="provenance.context_admissibility",
        surfaces=[
            "scan_prose_boundary()",
            "Profiles: final-prose / brief-light / paper-full / prompt-template / audit / methodology / consultation_report / changelog",
        ],
        notes="v0.9 added prompt-template profile after empirical calibration on real briefs.",
    ))

    rows.append(LayerStatus(
        layer_id="L7-G2",
        name="G2 Source & Warrant Check",
        status="BUILT",
        module="provenance.verify, provenance.grade, provenance.extract",
        surfaces=[
            "verify_claim()",
            "HeuristicGrader / LLMGrader / LocalLLMGrader / ClaudeCliGrader",
            "PROVENANCE_GRADER env override; claude-CLI subscription-over-API auto-select",
            "Salience-weighted load-bearing detection",
            "11 CLAIM_TRIGGERS (Phase 1): year/percentage/magnitude/statute/"
            "attribution/decision/superlative/causal/numeric_approx/named_body/comparison",
            "Per-profile unsupported-fraction HOLD thresholds (consolidate_verdict)",
        ],
        notes=(
            "Three graders: heuristic (default, free), Anthropic LLM (paid), "
            "Local LLM (free, OpenAI-compatible). Phase 1 (2026-06-11) added the "
            "decision trigger (closing the salience/detection misalignment) plus "
            "five categories (superlative, causal, numeric-approximation, "
            "named-body attribution, empirical comparison) with +0.30 salience "
            "weights for causal/comparison/body-attribution, and per-profile "
            "unsupported-fraction HOLD thresholds so an audit run cannot return a "
            "bare PASS with all claims unsupported."
        ),
    ))

    rows.append(LayerStatus(
        layer_id="L7-G3",
        name="G3 Non-Self-Grounding",
        status="BUILT",
        module="provenance.gates",
        surfaces=[
            "check_self_grounding()",
            "Model-family registry (Claude, GPT, Gemini, Llama, Grok, Mistral, Cohere)",
            "Informational FLAG per SPEC-L7-N003 (not BLOCK)",
        ],
        notes="Wired into warrantos CLI via --writer-model / --verifier-model.",
    ))

    rows.append(LayerStatus(
        layer_id="L7-G4",
        name="G4 Safety & Contamination",
        status="BUILT" if _module_has(
            "provenance.gates", "check_contamination"
        ) else "STARTER",
        module="provenance.gates, eval/corpus/contamination.jsonl",
        surfaces=[
            "check_contamination()",
            "8 generic prompt-injection patterns + 4 policy-domain patterns "
            "(legislative-format injection, authority impersonation, "
            "classification-laundering, output-override headings)",
            "corpus_completeness='domain-extended' flag in result",
            "Labelled corpus: eval/corpus/contamination.jsonl (24 items)",
        ],
        notes=(
            "v0.9 Phase 3 extended the generic starter set with policy-domain "
            "patterns and a 24-item labelled corpus "
            "(eval/corpus/contamination.jsonl), flipping corpus_completeness "
            "from 'starter' to 'domain-extended'. The list is still not "
            "exhaustive; production deployments SHOULD continue to extend it "
            "against their own documented threat model."
        ),
    ))

    rows.append(LayerStatus(
        layer_id="L7-G5",
        name="G5 Evaluation & Calibration",
        status="BUILT" if _module_has(
            "provenance.gates", "check_calibration", "_calibration_from_stored"
        ) else "STARTER",
        module="provenance.gates, eval/run_eval.py, cli.warrantos_cli",
        surfaces=[
            "check_calibration() [accepts live verdict rows OR a stored calibration.json]",
            "CLI: warrantos calibrate (runs eval/run_eval.py, writes .warrant/calibration.json)",
            "calibration.json: grader / corpus size / per-class recall / coverage estimate",
        ],
        notes=(
            "warrantos calibrate runs the grader against the labelled eval "
            "corpus and writes .warrant/calibration.json (grader, corpus "
            "size, per-class recall, coverage estimate). check_calibration() "
            "accepts either live verdict rows (Brier-with-explicit-coverage) "
            "or the stored calibration.json. Confidence coverage is typically "
            "0 with the offline HeuristicGrader (no confidence emitted); "
            "per-class recall is the meaningful measure until an LLM grader "
            "supplies numeric confidence."
        ),
    ))

    rows.append(LayerStatus(
        layer_id="L8",
        name="Human Review & Decision Authority",
        status="BUILT",
        module="provenance.overrides, provenance.footer",
        surfaces=[
            "record_override() [SPEC-L8-S004 structured rationale]",
            "enforce_single_actor_rule() [SPEC-L8-S003 SoD]",
            "render_override_footer() [SPEC-L8-S005 reader-facing]",
            "list_canonical_escalation_paths() [v0.9 taxonomy]",
            "Append-only via SQLite trigger [INV-004 v0.9]",
        ],
        notes="Escalation routing is a documented taxonomy not an automated workflow.",
    ))

    # ---------- Foundation row ----------
    # F-policy is BUILT when BOTH gaps that held it at PARTIAL are closed:
    #   1. a machine-readable role registry exists at runtime
    #      (provenance.roles with the six SPEC-F-S002 actor roles plus a
    #      validate_actor_identity() runtime check), AND
    #   2. the normative SPEC document is committed to the repository
    #      (docs/SPEC.md).
    # Both are checked here rather than assumed: the registry is checked by
    # importing it and confirming the six required role ids resolve; the
    # SPEC file is checked for presence on disk relative to the repo root.
    _roles_registry_built = _module_has(
        "provenance.roles",
        "ACTOR_ROLES", "REQUIRED_ACTOR_ROLE_IDS", "validate_actor_identity",
        "registry_to_dict",
    ) and _role_registry_complete()
    _spec_committed = _repo_file_exists("docs/SPEC.md")
    _f_policy_built = _roles_registry_built and _spec_committed

    rows.append(LayerStatus(
        layer_id="F-policy",
        name="Foundation: Policy & Role Definitions",
        status="BUILT" if _f_policy_built else "PARTIAL",
        module="provenance.roles; docs/SPEC.md; docs/STACK.md",
        surfaces=[
            "provenance.roles: 6 SPEC-F-S002 actor roles + validate_actor_identity()",
            "registry_to_dict() schema warrantos-roles/v1",
            "CBOM actor_identity field carries the six roles",
            "docs/SPEC.md (normative spec, RFC 2119) committed",
        ],
        notes=(
            "v0.9: machine-readable role registry (provenance.roles) "
            "enumerates the six SPEC-F-S002 actor roles and validates a "
            "CBOM actor_identity map at runtime; the normative SPEC "
            "document is committed at docs/SPEC.md. Both gaps that held "
            "this row at PARTIAL are closed."
        ) if _f_policy_built else (
            "Roles documented and carried by the CBOM actor_identity field, "
            "but the runtime registry (provenance.roles) and/or the "
            "committed normative SPEC (docs/SPEC.md) are not both present "
            "in this install."
        ),
    ))

    rows.append(LayerStatus(
        layer_id="F-classification",
        name="Foundation: Data Classification (sensitivity tiers)",
        status="BUILT" if _module_has(
            "provenance.classification",
            "SensitivityTier", "classify_sensitivity", "gate_sensitivity",
            "SensitivityBlock", "DEFAULT_TIERS",
        ) else "NOT_BUILT",
        module="provenance.classification",
        surfaces=[
            "SensitivityTier dataclass + 4-tier DEFAULT_TIERS (Public/Official/Sensitive/Credentials)",
            "classify_sensitivity() [starter keyword heuristics]",
            "gate_sensitivity() / SensitivityBlock [fail-closed]",
            "CLI: warrantos check --sensitivity-check",
        ],
        notes=(
            "4-tier default registry mirrors the reference adopter's data "
            "gate. Keyword heuristics (Cabinet, ministerial, legal advice, "
            "Crown Solicitor, HR/PIP/termination, $NNNM/B budget markers, "
            "credential patterns) are a documented STARTER set; production "
            "deployments SHALL extend them with a domain taxonomy. Unmatched "
            "text defaults to Official, never silently Public."
        ),
    ))

    rows.append(LayerStatus(
        layer_id="F-audit",
        name="Foundation: Audit Logging",
        status="BUILT",
        module="SQLite ledger + per-run JSON artefacts",
        surfaces=[
            ".warrant/provenance.db",
            ".warrant/runs/<run_id>/cbom.json + verdict.json + ...",
            "publish-gate-shadow.log (shadow observer)",
        ],
        notes="Audit lives in SQLite (cross-run) + per-run JSON (single-run snapshot) + shadow log (observation history).",
    ))

    rows.append(LayerStatus(
        layer_id="F-integrity",
        name="Foundation: Ledger Integrity & Attestation",
        status="BUILT" if _module_has(
            "provenance.merkle", "ledger_root", "build_checkpoint"
        ) and _module_has(
            "provenance.warrant_bundle", "create_warrant", "verify_warrant"
        ) else "PARTIAL",
        module="provenance.merkle, provenance.attestation, provenance.warrant_bundle",
        surfaces=[
            "merkle.ledger_root() / build_checkpoint() [RFC 6962 style, stdlib]",
            "attestation.sign_checkpoint() / verify_checkpoint() [Ed25519, [attestation] extra]",
            "warrant_bundle.create_warrant() / verify_warrant() [fail-closed]",
            "CLI: warrantos attest / verify-external",
            "web/verify.html [client-side verifier, byte-for-byte parity]",
        ],
        notes="Stdlib Merkle integrity + fail-closed .warrant verification need no key; Ed25519 signing needs the optional [attestation] extra. Envelope is project-defined (DSSE/COSE migration under consideration).",
    ))

    rows.append(LayerStatus(
        layer_id="F-retention",
        name="Foundation: Retention & Deletion (tombstones)",
        status="BUILT" if _module_has(
            "provenance.retention",
            "set_window", "list_expired", "tombstone_run", "list_tombstones",
        ) else "NOT_BUILT",
        module="provenance.retention, schema/provenance.sql",
        surfaces=[
            "retention_window_days column on provenance_run",
            "provenance_tombstone + retention_window append-only tables",
            "set_window() / list_expired() / tombstone_run() / list_tombstones()",
            "CLI: warrantos retention set-window|list-expired|tombstone-run|list",
        ],
        notes=(
            "INV-011 implemented as APPEND-ONLY tombstones in v0.9 Phase 3: "
            "no hard delete. Expiry of a retention window appends a tombstone "
            "marking the run logically retired while preserving every ledger "
            "row (INV-004 append-only is never violated). Per-run windows are "
            "set at run creation (column) or appended later via set_window() "
            "(latest override wins). Adopters still specify the window."
        ),
    ))

    # F-compliance is BUILT when the documentation surface is complete:
    #   1. the normative SPEC document is committed (docs/SPEC.md), AND
    #   2. a control-mapping document is committed (docs/COMPLIANCE.md) that
    #      maps the enforced controls to ISO/IEC 42001 and the NIST AI RMF.
    # BUILT here means the documented-mapping ceiling, NOT certified
    # conformance. The honest ceiling for this row is "committed SPEC +
    # documented self-assessment mapping"; accredited certification is
    # explicitly out of scope (see docs/COMPLIANCE.md §5). Both artefacts are
    # checked for presence on disk rather than assumed.
    _compliance_doc = _repo_file_exists("docs/COMPLIANCE.md")
    _f_compliance_built = _spec_committed and _compliance_doc
    rows.append(LayerStatus(
        layer_id="F-compliance",
        name="Foundation: Compliance & Standards (ISO / NIST / Gov)",
        status="BUILT" if _f_compliance_built else "PARTIAL",
        module="docs/SPEC.md, docs/COMPLIANCE.md; SPEC-IDs grep-traceable in code/tests",
        surfaces=[
            "docs/SPEC.md (normative spec, RFC 2119) committed",
            "docs/COMPLIANCE.md: control mapping to ISO/IEC 42001 + NIST AI RMF + AU/QLD gov",
            "RFC 2119 conformance language; SPEC-ID references grep-traceable (SPEC §8)",
        ],
        notes=(
            "BUILT = documented-mapping ceiling: the normative SPEC "
            "(docs/SPEC.md) and a self-assessment control mapping "
            "(docs/COMPLIANCE.md) are both committed, mapping the enforced "
            "controls (gates G1-G5, override ledger, classification, "
            "retention/tombstones, Merkle/attestation) to ISO/IEC 42001 and "
            "NIST AI RMF clauses. This is NOT certified conformance: no "
            "accredited body has assessed the project, and certification is "
            "explicitly out of scope (docs/COMPLIANCE.md disclaimer + §5). "
            "There is still no automated SPEC-ID conformance check; the "
            "grep-traceable SPEC IDs in code and tests remain the technical "
            "compliance surface."
        ) if _f_compliance_built else (
            "No automated compliance check; the SPEC IDs in code and tests "
            "are the compliance surface. The normative SPEC (docs/SPEC.md) "
            "and/or the control-mapping document (docs/COMPLIANCE.md) are not "
            "both present in this install."
        ),
    ))

    rows.append(LayerStatus(
        layer_id="F-override",
        name="Foundation: Human Override",
        status="BUILT",
        module="provenance.overrides",
        surfaces=[
            "human_override SQLite table",
            "SPEC-L8-S002/S003/S004/S005 enforced",
            "INV-004 append-only trigger",
        ],
        notes="Most complete of the foundation items.",
    ))

    # F-metrics is BUILT when the shadow-observation log is not just
    # appended but AGGREGATED at runtime: the metrics module computes a
    # verdict distribution, an unsupported-claim rate over the window,
    # and a trend, and can write .warrant/metrics.json. Checked by
    # importing provenance.metrics and confirming the aggregation
    # entry points resolve.
    _metrics_built = _module_has(
        "provenance.metrics",
        "aggregate_shadow_log", "write_metrics_json",
        "ShadowMetrics", "calibration_supplement",
    )
    rows.append(LayerStatus(
        layer_id="F-metrics",
        name="Foundation: Metrics & Monitoring",
        status="BUILT" if _metrics_built else "PARTIAL",
        module="provenance.metrics, tools/warrantos-shadow-observe.py, cli.warrantos_cli",
        surfaces=[
            "Daily shadow observer (Task Scheduler at 07:00)",
            "publish-gate-shadow.log JSON-line append",
            "metrics.aggregate_shadow_log() [verdict distribution, "
            "unsupported-claim rate, improving/worsening/stable trend]",
            "metrics.write_metrics_json() -> .warrant/metrics.json",
            "CLI: warrantos metrics [--log --out --no-write --json]",
            "gates.calibration_with_monitoring() links the G5 corpus "
            "calibration to the shadow-log monitoring signal",
        ],
        notes=(
            "v0.9.1: the shadow log is now aggregated, not just appended. "
            "provenance.metrics.aggregate_shadow_log() reads the JSON-lines "
            "log and computes the verdict distribution, the unsupported-claim "
            "rate over the observation window, and a simple "
            "improving/worsening/stable trend (earlier vs later half of the "
            "observed rows); a missing or empty log yields an honest empty "
            "aggregate (observed=0, trend=insufficient_data) rather than an "
            "error. `warrantos metrics` writes .warrant/metrics.json. The G5 "
            "link is gates.calibration_with_monitoring(), which keeps the "
            "corpus calibration and the operational shadow-rate as SEPARATE "
            "surfaces (the shadow rate is a monitoring signal, not a "
            "Brier-style confidence calibration). Tested in "
            "tests/test_metrics.py."
        ) if _metrics_built else (
            "Shadow log is the closest thing to metrics today. A full "
            "metrics pipeline is v1.0+."
        ),
    ))

    return rows


def render_markdown(rows: Optional[List[LayerStatus]] = None) -> str:
    """Render the status report as Markdown."""
    if rows is None:
        rows = collect_status()

    lines = [
        "# WarrantOS layer status",
        "",
        "Auto-generated by `warrantos status --markdown` or "
        "`python -c \"from provenance.status import render_markdown; print(render_markdown())\"`.",
        "",
        "Status values: **BUILT** (full SHALL coverage + tests + runtime enforcement); "
        "**PARTIAL** (code present, some SHALLs discipline-only); "
        "**STARTER** (built but documented as needing extension before production use); "
        "**NOT_BUILT** (documented v1.0+ deferral).",
        "",
        "| Layer | Status | Module | Notes |",
        "|---|---|---|---|",
    ]
    for r in rows:
        notes = r.notes.replace("|", "\\|")
        module = r.module.replace("|", "\\|")
        lines.append(
            "| **%s %s** | `%s` | `%s` | %s |" % (
                r.layer_id, r.name.replace("|", "\\|"), r.status, module, notes
            )
        )

    # Summary counts.
    counts: Dict[str, int] = {}
    for r in rows:
        counts[r.status] = counts.get(r.status, 0) + 1
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    for status in ("BUILT", "PARTIAL", "STARTER", "NOT_BUILT"):
        if counts.get(status):
            lines.append("- **%s**: %d" % (status, counts[status]))
    lines.append("")
    lines.append(
        "Generated against the running install of `provenance.*`. Re-run "
        "after each version bump to refresh."
    )
    return "\n".join(lines) + "\n"


def render_text(rows: Optional[List[LayerStatus]] = None) -> str:
    """Render the status report as a plain-text table for stdout."""
    if rows is None:
        rows = collect_status()
    lines = []
    lines.append("WarrantOS layer status")
    lines.append("=" * 80)
    for r in rows:
        lines.append(
            "%-12s %-12s  %s" % (r.layer_id, r.status, r.name)
        )
    lines.append("")
    counts: Dict[str, int] = {}
    for r in rows:
        counts[r.status] = counts.get(r.status, 0) + 1
    for status in ("BUILT", "PARTIAL", "STARTER", "NOT_BUILT"):
        if counts.get(status):
            lines.append("  %-10s %d" % (status, counts[status]))
    return "\n".join(lines)
