"""provenance.status: per-layer conformance dashboard.

Reports the running install's status against the eight-layer
WarrantOS architecture diagram plus the foundation row. Output
states per layer:

- **BUILT**: full SPEC SHALLs met with code + test coverage +
  runtime enforcement.
- **PARTIAL**: code present; one or more SHALLs deferred or
  discipline-only.
- **STARTER**: code present but explicitly documented as a starter
  surface that needs corpus / threat-model extension before
  production use.
- **NOT BUILT**: no code; documented as a v1.0+ deferral.

The status data is generated by inspecting the installed modules
(presence of classes, functions, entry points). It is not a test
suite; failing tests still report the module as present. The intent
is to give a fresh contributor or auditor a single-screen view of
which layers are real today.

Stdlib only. Python 3.8 compatible.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from importlib import import_module
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class LayerStatus:
    """Status of one layer / gate / foundation item."""

    layer_id: str
    name: str
    status: str  # BUILT | PARTIAL | STARTER | NOT_BUILT
    module: str
    surfaces: List[str] = field(default_factory=list)
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "layer_id": self.layer_id,
            "name": self.name,
            "status": self.status,
            "module": self.module,
            "surfaces": list(self.surfaces),
            "notes": self.notes,
        }


def _module_has(module_path: str, *names: str) -> bool:
    """Return True if every name exists on the named module.

    Tolerant: returns False on ImportError or AttributeError so that a
    partially-installed package still produces a useful status report.
    """
    try:
        mod = import_module(module_path)
    except ImportError:
        return False
    for n in names:
        if not hasattr(mod, n):
            return False
    return True


def collect_status() -> List[LayerStatus]:
    """Return the full per-layer status list.

    Each layer's status is computed against the running install:
    presence of the relevant module symbols decides BUILT vs the
    documented partial / starter / not-built reading.
    """
    rows: List[LayerStatus] = []

    # ---------- Eight layers ----------
    rows.append(LayerStatus(
        layer_id="L1",
        name="Context Classification (11 classes)",
        status="BUILT" if _module_has(
            "provenance.context_admissibility", "classify_context"
        ) else "NOT_BUILT",
        module="provenance.context_admissibility",
        surfaces=["classify_context()", "ContextItem dataclass"],
        notes="11 canonical SPEC §2.2 classes via regex; SPEC-L1-S005 review-role gating via source_agent kwarg.",
    ))

    rows.append(LayerStatus(
        layer_id="L2",
        name="Provenance Ledger (5 sub-ledgers + override)",
        status="BUILT" if _module_has(
            "provenance.ledger_write", "enable_append_only_triggers"
        ) else "PARTIAL",
        module="provenance.ledger_write, provenance.overrides",
        surfaces=[
            "schema/provenance.sql",
            "enable_append_only_triggers() [INV-004 ENFORCED v0.9]",
            "human_override trigger installed via overrides.py CREATE TABLE",
        ],
        notes="INV-004 storage-level enforcement added in v0.9 via SQLite BEFORE UPDATE triggers.",
    ))

    rows.append(LayerStatus(
        layer_id="L3",
        name="Applied Insight Compiler",
        status="BUILT" if _module_has(
            "provenance.ledger_write", "persist_context_transform"
        ) else "PARTIAL",
        module="provenance.context_admissibility, provenance.ledger_write",
        surfaces=["derive_requirement()", "persist_context_transform()"],
        notes="SPEC-L3-N001 closure: persist_context_transform() writes the ledger row per derived requirement (v0.9).",
    ))

    rows.append(LayerStatus(
        layer_id="L4",
        name="Context Admissibility Engine (6 actor roles)",
        status="BUILT",
        module="provenance.context_admissibility, provenance.cbom",
        surfaces=[
            "ContextItem.can_be_seen_by / cannot_be_seen_by",
            "CBOM.actor_identity (6 roles per SPEC §5.2)",
        ],
        notes="Per-item flags + 6-role actor identity in CBOM v0.2.",
    ))

    rows.append(LayerStatus(
        layer_id="L5",
        name="Clean-Room Writer Pack (5 sections)",
        status="BUILT" if _module_has(
            "provenance.writer_pack", "compile_writer_pack"
        ) else "NOT_BUILT",
        module="provenance.writer_pack",
        surfaces=[
            "compile_writer_pack()",
            "WriterPack dataclass with 5 SPEC §6.2 sections",
        ],
        notes="Clean Brief / Approved Sources / Style Rules / Acceptance Tests / Banned Residue.",
    ))

    rows.append(LayerStatus(
        layer_id="L6",
        name="Clean-Room Generation (discipline + subprocess isolation)",
        status="BUILT" if _module_has(
            "provenance.clean_room", "run_clean_room_subprocess"
        ) else "PARTIAL",
        module="provenance.clean_room",
        surfaces=[
            "prepare_invocation() [discipline mode, SPEC-L6-S001]",
            "run_clean_room_subprocess() [Level 2, SPEC-L6-R001]",
        ],
        notes="WarrantOS does not call any LLM itself. The caller invokes their writer model through the InvocationPlan.",
    ))

    # ---------- Layer 7: five gates ----------
    rows.append(LayerStatus(
        layer_id="L7-G1",
        name="G1 Prose Boundary",
        status="BUILT",
        module="provenance.context_admissibility",
        surfaces=[
            "scan_prose_boundary()",
            "Profiles: final-prose / brief-light / paper-full / prompt-template / audit / methodology / consultation_report / changelog",
        ],
        notes="v0.9 added prompt-template profile after empirical calibration on real briefs.",
    ))

    rows.append(LayerStatus(
        layer_id="L7-G2",
        name="G2 Source & Warrant Check",
        status="BUILT",
        module="provenance.verify, provenance.grade",
        surfaces=[
            "verify_claim()",
            "HeuristicGrader / LLMGrader / LocalLLMGrader",
            "Salience-weighted load-bearing detection",
        ],
        notes="Three graders: heuristic (default, free), Anthropic LLM (paid), Local LLM (free, OpenAI-compatible).",
    ))

    rows.append(LayerStatus(
        layer_id="L7-G3",
        name="G3 Non-Self-Grounding",
        status="BUILT",
        module="provenance.gates",
        surfaces=[
            "check_self_grounding()",
            "Model-family registry (Claude, GPT, Gemini, Llama, Grok, Mistral, Cohere)",
            "Informational FLAG per SPEC-L7-N003 (not BLOCK)",
        ],
        notes="Wired into warrantos CLI via --writer-model / --verifier-model.",
    ))

    rows.append(LayerStatus(
        layer_id="L7-G4",
        name="G4 Safety & Contamination",
        status="STARTER",
        module="provenance.gates",
        surfaces=[
            "check_contamination()",
            "8 starter prompt-injection patterns",
            "corpus_completeness='starter' flag in result",
        ],
        notes="Production deployments SHALL replace or extend with a documented threat-model corpus. v1.0 deferral.",
    ))

    rows.append(LayerStatus(
        layer_id="L7-G5",
        name="G5 Evaluation & Calibration",
        status="STARTER",
        module="provenance.gates",
        surfaces=[
            "check_calibration() [Brier-with-explicit-coverage]",
        ],
        notes="Coverage typically 0 with HeuristicGrader (no confidence emitted). Becomes meaningful with LLM grader.",
    ))

    rows.append(LayerStatus(
        layer_id="L8",
        name="Human Review & Decision Authority",
        status="BUILT",
        module="provenance.overrides, provenance.footer",
        surfaces=[
            "record_override() [SPEC-L8-S004 structured rationale]",
            "enforce_single_actor_rule() [SPEC-L8-S003 SoD]",
            "render_override_footer() [SPEC-L8-S005 reader-facing]",
            "list_canonical_escalation_paths() [v0.9 taxonomy]",
            "Append-only via SQLite trigger [INV-004 v0.9]",
        ],
        notes="Escalation routing is a documented taxonomy not an automated workflow.",
    ))

    # ---------- Foundation row ----------
    rows.append(LayerStatus(
        layer_id="F-policy",
        name="Foundation: Policy & Role Definitions",
        status="PARTIAL",
        module="docs/STACK.md; SPEC IDs in code",
        surfaces=["6-role taxonomy documented; actor_identity field enforced in CBOM"],
        notes="Roles are documented and the CBOM actor_identity field carries them. A runtime registry is not built. The normative SPEC document is not yet committed to this repository; SPEC IDs in code and tests are the source of truth at v0.9.0b1.",
    ))

    rows.append(LayerStatus(
        layer_id="F-classification",
        name="Foundation: Data Classification (sensitivity tiers)",
        status="NOT_BUILT",
        module="-",
        surfaces=[],
        notes="Requires a domain-specific sensitivity taxonomy from the adopter. v1.0 deferral; cannot be fabricated.",
    ))

    rows.append(LayerStatus(
        layer_id="F-audit",
        name="Foundation: Audit Logging",
        status="BUILT",
        module="SQLite ledger + per-run JSON artefacts",
        surfaces=[
            ".warrant/provenance.db",
            ".warrant/runs/<run_id>/cbom.json + verdict.json + ...",
            "publish-gate-shadow.log (shadow observer)",
        ],
        notes="Audit lives in SQLite (cross-run) + per-run JSON (single-run snapshot) + shadow log (observation history).",
    ))

    rows.append(LayerStatus(
        layer_id="F-integrity",
        name="Foundation: Ledger Integrity & Attestation",
        status="BUILT" if _module_has(
            "provenance.merkle", "ledger_root", "build_checkpoint"
        ) and _module_has(
            "provenance.warrant_bundle", "create_warrant", "verify_warrant"
        ) else "PARTIAL",
        module="provenance.merkle, provenance.attestation, provenance.warrant_bundle",
        surfaces=[
            "merkle.ledger_root() / build_checkpoint() [RFC 6962 style, stdlib]",
            "attestation.sign_checkpoint() / verify_checkpoint() [Ed25519, [attestation] extra]",
            "warrant_bundle.create_warrant() / verify_warrant() [fail-closed]",
            "CLI: warrantos attest / verify-external",
            "web/verify.html [client-side verifier, byte-for-byte parity]",
        ],
        notes="Stdlib Merkle integrity + fail-closed .warrant verification need no key; Ed25519 signing needs the optional [attestation] extra. Envelope is project-defined (DSSE/COSE migration under consideration).",
    ))

    rows.append(LayerStatus(
        layer_id="F-retention",
        name="Foundation: Retention & Deletion (tombstones)",
        status="NOT_BUILT",
        module="-",
        surfaces=[],
        notes="INV-011 PROPOSITION. Requires the adopter to specify retention windows. v1.0 deferral.",
    ))

    rows.append(LayerStatus(
        layer_id="F-compliance",
        name="Foundation: Compliance & Standards (ISO / NIST / Gov)",
        status="PARTIAL",
        module="SPEC IDs in code (SPEC document not yet in repo)",
        surfaces=["RFC 2119 conformance language; SPEC-ID references in tests and modules"],
        notes="No automated compliance check; the SPEC IDs in code and tests are the compliance surface. The normative SPEC document is in preparation and will be committed alongside a future release.",
    ))

    rows.append(LayerStatus(
        layer_id="F-override",
        name="Foundation: Human Override",
        status="BUILT",
        module="provenance.overrides",
        surfaces=[
            "human_override SQLite table",
            "SPEC-L8-S002/S003/S004/S005 enforced",
            "INV-004 append-only trigger",
        ],
        notes="Most complete of the foundation items.",
    ))

    rows.append(LayerStatus(
        layer_id="F-metrics",
        name="Foundation: Metrics & Monitoring",
        status="PARTIAL",
        module="tools/warrantos-shadow-observe.py",
        surfaces=[
            "Daily shadow observer (Task Scheduler at 07:00)",
            "publish-gate-shadow.log JSON-line append",
        ],
        notes="Shadow log is the closest thing to metrics today. A full metrics pipeline is v1.0+.",
    ))

    return rows


def render_markdown(rows: Optional[List[LayerStatus]] = None) -> str:
    """Render the status report as Markdown."""
    if rows is None:
        rows = collect_status()

    lines = [
        "# WarrantOS layer status",
        "",
        "Auto-generated by `warrantos status --markdown` or "
        "`python -c \"from provenance.status import render_markdown; print(render_markdown())\"`.",
        "",
        "Status values: **BUILT** (full SHALL coverage + tests + runtime enforcement); "
        "**PARTIAL** (code present, some SHALLs discipline-only); "
        "**STARTER** (built but documented as needing extension before production use); "
        "**NOT_BUILT** (documented v1.0+ deferral).",
        "",
        "| Layer | Status | Module | Notes |",
        "|---|---|---|---|",
    ]
    for r in rows:
        notes = r.notes.replace("|", "\\|")
        module = r.module.replace("|", "\\|")
        lines.append(
            "| **%s %s** | `%s` | `%s` | %s |" % (
                r.layer_id, r.name.replace("|", "\\|"), r.status, module, notes
            )
        )

    # Summary counts.
    counts: Dict[str, int] = {}
    for r in rows:
        counts[r.status] = counts.get(r.status, 0) + 1
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    for status in ("BUILT", "PARTIAL", "STARTER", "NOT_BUILT"):
        if counts.get(status):
            lines.append("- **%s**: %d" % (status, counts[status]))
    lines.append("")
    lines.append(
        "Generated against the running install of `provenance.*`. Re-run "
        "after each version bump to refresh."
    )
    return "\n".join(lines) + "\n"


def render_text(rows: Optional[List[LayerStatus]] = None) -> str:
    """Render the status report as a plain-text table for stdout."""
    if rows is None:
        rows = collect_status()
    lines = []
    lines.append("WarrantOS layer status")
    lines.append("=" * 80)
    for r in rows:
        lines.append(
            "%-12s %-12s  %s" % (r.layer_id, r.status, r.name)
        )
    lines.append("")
    counts: Dict[str, int] = {}
    for r in rows:
        counts[r.status] = counts.get(r.status, 0) + 1
    for status in ("BUILT", "PARTIAL", "STARTER", "NOT_BUILT"):
        if counts.get(status):
            lines.append("  %-10s %d" % (status, counts[status]))
    return "\n".join(lines)
